services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    networks:
      www-my6sense:
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./mysql/my.cnf:/usr/local/etc/mysql/mysql.conf.d/mysqld.cnf:ro
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  web:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    networks:
      www-my6sense:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../backend:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro

  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: php
    env_file:
      - variables/xdebug.env
    networks:
      www-my6sense:
    volumes:
      - ../backend:/var/www
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway

  node:
    networks:
      www-my6sense:
    image: node:20.7.0
    container_name: node
    volumes:
      - ../frontend:/var/www/html
    working_dir: /var/www/html
    command: "npm run start:prod"
    restart: always

  mail:
    image: mailhog/mailhog
    container_name: mail
    networks:
      www-my6sense:
    ports:
      - "1025:1025"
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      www-my6sense:
    ports:
      - "8081:80"

  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      www-my6sense:
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  redis:
    image: redis
    container_name: redis
    networks:
      www-my6sense:
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  rabbitmq:
    image: rabbitmq:3.9.5-management-alpine
    container_name: rabbitmq
    networks:
      www-my6sense:
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    restart: always

networks:
  www-my6sense:
volumes:
  mysql_volume:
  redis_volume:
  mongo_volume:
  rabbitmq_volume:
